---
services:
  
  geth:
    image: ethereum/client-go:$VERSION_GETH
    ports:
      - name: jsonrpc
        target: 8545
        published: 8545
    volumes:
      - type: bind
        source: ./data/
        target: /tmp/datadir/
    environment:
      GETH_DEV: true
      GETH_HTTP: true
      GETH_HTTP_ADDR: 0.0.0.0
      GETH_DATADIR: /tmp/datadir/
