#!/bin/sh -euC

ENV_FILE=.env

bootnode_ip="$(docker compose exec node1 awk '/^172/{print $1}' /etc/hosts)"
enode_url="$(docker compose logs node1 \
    | awk '/Enode URL/{print $14}' \
    | sed "s/127\.0\.0\.1/$bootnode_ip/")"
>&2 echo "bootnode enode URL is $enode_url"
if grep -q ^BOOTNODE_ENODE_URL= "$ENV_FILE"; then
	>&2 echo "Replacing value of BOOTNODE_ENODE_URL in $ENV_FILE"
	sed -i \
	    "s|^BOOTNODE_ENODE_URL=.*|BOOTNODE_ENODE_URL=$enode_url|" \
	    "$ENV_FILE"
else
	>&2 echo "Setting BOOTNODE_ENODE_URL in $ENV_FILE"
	echo "BOOTNODE_ENODE_URL=$enode_url" >>"$ENV_FILE"
fi
